services:
  db:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: postgres         # Change this to your preferred username
      POSTGRES_PASSWORD: your_password # Change this to your preferred password
      POSTGRES_DB: postgres       # Change this to your preferred database name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
