services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    restart: always
    user: "1000:1000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password}
      PGDATA: /var/lib/postgresql/data # Data directory for PostgreSQL
    volumes:
      - './timescale_data:/var/lib/postgresql/data'
      - './postgresql.conf:/etc/postgresql/postgresql.conf'
    network_mode: host
