// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $CookiePolicy from "./routes/CookiePolicy.tsx";
import * as $PrivacyPolicy from "./routes/PrivacyPolicy.tsx";
import * as $TermsOfService from "./routes/TermsOfService.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_data from "./routes/api/data.tsx";
import * as $api_signup from "./routes/api/signup.tsx";
import * as $dashboards_accounts from "./routes/dashboards/accounts.tsx";
import * as $dashboards_network from "./routes/dashboards/network.tsx";
import * as $dashboards_transactions from "./routes/dashboards/transactions.tsx";
import * as $index from "./routes/index.tsx";
import * as $CommunitySignup from "./islands/CommunitySignup.tsx";
import * as $SocketManager from "./islands/SocketManager.tsx";
import * as $dashboards_accounts_Accounts from "./islands/dashboards/accounts/Accounts.tsx";
import * as $dashboards_accounts_charts_AccountDormancy from "./islands/dashboards/accounts/charts/AccountDormancy.tsx";
import * as $dashboards_accounts_charts_AccountMoneyRecency from "./islands/dashboards/accounts/charts/AccountMoneyRecency.tsx";
import * as $dashboards_accounts_charts_AnimalTierTrends from "./islands/dashboards/accounts/charts/AnimalTierTrends.tsx";
import * as $dashboards_accounts_charts_BasicStats from "./islands/dashboards/accounts/charts/BasicStats.tsx";
import * as $dashboards_accounts_charts_NetworkActivityRatio from "./islands/dashboards/accounts/charts/NetworkActivityRatio.tsx";
import * as $dashboards_accounts_charts_RepChangeDistro from "./islands/dashboards/accounts/charts/RepChangeDistro.tsx";
import * as $dashboards_accounts_charts_TierBalancesDistro from "./islands/dashboards/accounts/charts/TierBalancesDistro.tsx";
import * as $dashboards_accounts_charts_TopTierBalancesDistro from "./islands/dashboards/accounts/charts/TopTierBalancesDistro.tsx";
import * as $dashboards_accounts_charts_TransactionBalanceDistro from "./islands/dashboards/accounts/charts/TransactionBalanceDistro.tsx";
import * as $dashboards_accounts_models from "./islands/dashboards/accounts/models.ts";
import * as $dashboards_transactions_InfoBar from "./islands/dashboards/transactions/InfoBar.tsx";
import * as $dashboards_transactions_PriceTracker from "./islands/dashboards/transactions/PriceTracker.tsx";
import * as $dashboards_transactions_Transactions from "./islands/dashboards/transactions/Transactions.tsx";
import * as $dashboards_transactions_charts_ChartsContainer from "./islands/dashboards/transactions/charts/ChartsContainer.tsx";
import * as $dashboards_transactions_charts_NanoAccountsChart from "./islands/dashboards/transactions/charts/NanoAccountsChart.tsx";
import * as $dashboards_transactions_charts_NanoConfirmationsChart from "./islands/dashboards/transactions/charts/NanoConfirmationsChart.tsx";
import * as $dashboards_transactions_charts_NanoDistributionChart from "./islands/dashboards/transactions/charts/NanoDistributionChart.tsx";
import * as $dashboards_transactions_charts_NanoPricesChart from "./islands/dashboards/transactions/charts/NanoPricesChart.tsx";
import * as $dashboards_transactions_charts_NanoVolumeChart from "./islands/dashboards/transactions/charts/NanoVolumeChart.tsx";
import * as $dashboards_transactions_charts_chart_data from "./islands/dashboards/transactions/charts/chart_data.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/CookiePolicy.tsx": $CookiePolicy,
    "./routes/PrivacyPolicy.tsx": $PrivacyPolicy,
    "./routes/TermsOfService.tsx": $TermsOfService,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/data.tsx": $api_data,
    "./routes/api/signup.tsx": $api_signup,
    "./routes/dashboards/accounts.tsx": $dashboards_accounts,
    "./routes/dashboards/network.tsx": $dashboards_network,
    "./routes/dashboards/transactions.tsx": $dashboards_transactions,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CommunitySignup.tsx": $CommunitySignup,
    "./islands/SocketManager.tsx": $SocketManager,
    "./islands/dashboards/accounts/Accounts.tsx": $dashboards_accounts_Accounts,
    "./islands/dashboards/accounts/charts/AccountDormancy.tsx":
      $dashboards_accounts_charts_AccountDormancy,
    "./islands/dashboards/accounts/charts/AccountMoneyRecency.tsx":
      $dashboards_accounts_charts_AccountMoneyRecency,
    "./islands/dashboards/accounts/charts/AnimalTierTrends.tsx":
      $dashboards_accounts_charts_AnimalTierTrends,
    "./islands/dashboards/accounts/charts/BasicStats.tsx":
      $dashboards_accounts_charts_BasicStats,
    "./islands/dashboards/accounts/charts/NetworkActivityRatio.tsx":
      $dashboards_accounts_charts_NetworkActivityRatio,
    "./islands/dashboards/accounts/charts/RepChangeDistro.tsx":
      $dashboards_accounts_charts_RepChangeDistro,
    "./islands/dashboards/accounts/charts/TierBalancesDistro.tsx":
      $dashboards_accounts_charts_TierBalancesDistro,
    "./islands/dashboards/accounts/charts/TopTierBalancesDistro.tsx":
      $dashboards_accounts_charts_TopTierBalancesDistro,
    "./islands/dashboards/accounts/charts/TransactionBalanceDistro.tsx":
      $dashboards_accounts_charts_TransactionBalanceDistro,
    "./islands/dashboards/accounts/models.ts": $dashboards_accounts_models,
    "./islands/dashboards/transactions/InfoBar.tsx":
      $dashboards_transactions_InfoBar,
    "./islands/dashboards/transactions/PriceTracker.tsx":
      $dashboards_transactions_PriceTracker,
    "./islands/dashboards/transactions/Transactions.tsx":
      $dashboards_transactions_Transactions,
    "./islands/dashboards/transactions/charts/ChartsContainer.tsx":
      $dashboards_transactions_charts_ChartsContainer,
    "./islands/dashboards/transactions/charts/NanoAccountsChart.tsx":
      $dashboards_transactions_charts_NanoAccountsChart,
    "./islands/dashboards/transactions/charts/NanoConfirmationsChart.tsx":
      $dashboards_transactions_charts_NanoConfirmationsChart,
    "./islands/dashboards/transactions/charts/NanoDistributionChart.tsx":
      $dashboards_transactions_charts_NanoDistributionChart,
    "./islands/dashboards/transactions/charts/NanoPricesChart.tsx":
      $dashboards_transactions_charts_NanoPricesChart,
    "./islands/dashboards/transactions/charts/NanoVolumeChart.tsx":
      $dashboards_transactions_charts_NanoVolumeChart,
    "./islands/dashboards/transactions/charts/chart_data.ts":
      $dashboards_transactions_charts_chart_data,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
