// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $accounts from "./routes/accounts.tsx";
import * as $api_data from "./routes/api/data.tsx";
import * as $cookie_policy from "./routes/cookie_policy.tsx";
import * as $index from "./routes/index.tsx";
import * as $network from "./routes/network.tsx";
import * as $privacy_policy from "./routes/privacy_policy.tsx";
import * as $terms_of_service from "./routes/terms_of_service.tsx";
import * as $transactions from "./routes/transactions.tsx";
import * as $Accounts from "./islands/Accounts.tsx";
import * as $InfoBar from "./islands/InfoBar.tsx";
import * as $PriceTracker from "./islands/PriceTracker.tsx";
import * as $SocketManager from "./islands/SocketManager.tsx";
import * as $Transactions from "./islands/Transactions.tsx";
import * as $charts_ChartsContainer from "./islands/charts/ChartsContainer.tsx";
import * as $charts_NanoAccountsChart from "./islands/charts/NanoAccountsChart.tsx";
import * as $charts_NanoConfirmationsChart from "./islands/charts/NanoConfirmationsChart.tsx";
import * as $charts_NanoDistributionChart from "./islands/charts/NanoDistributionChart.tsx";
import * as $charts_NanoPricesChart from "./islands/charts/NanoPricesChart.tsx";
import * as $charts_NanoVolumeChart from "./islands/charts/NanoVolumeChart.tsx";
import * as $charts_chart_data from "./islands/charts/chart_data.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/accounts.tsx": $accounts,
    "./routes/api/data.tsx": $api_data,
    "./routes/cookie_policy.tsx": $cookie_policy,
    "./routes/index.tsx": $index,
    "./routes/network.tsx": $network,
    "./routes/privacy_policy.tsx": $privacy_policy,
    "./routes/terms_of_service.tsx": $terms_of_service,
    "./routes/transactions.tsx": $transactions,
  },
  islands: {
    "./islands/Accounts.tsx": $Accounts,
    "./islands/InfoBar.tsx": $InfoBar,
    "./islands/PriceTracker.tsx": $PriceTracker,
    "./islands/SocketManager.tsx": $SocketManager,
    "./islands/Transactions.tsx": $Transactions,
    "./islands/charts/ChartsContainer.tsx": $charts_ChartsContainer,
    "./islands/charts/NanoAccountsChart.tsx": $charts_NanoAccountsChart,
    "./islands/charts/NanoConfirmationsChart.tsx":
      $charts_NanoConfirmationsChart,
    "./islands/charts/NanoDistributionChart.tsx": $charts_NanoDistributionChart,
    "./islands/charts/NanoPricesChart.tsx": $charts_NanoPricesChart,
    "./islands/charts/NanoVolumeChart.tsx": $charts_NanoVolumeChart,
    "./islands/charts/chart_data.ts": $charts_chart_data,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
