node_ws_url = "ws://192.168.1.70:7078"
healthcheck_port = 8080

[nano_price_caller]
interval_ms = 30000
supported_currencies = [
    'AED',
    'ARS',
    'AUD',
    'BRL',
    'CHF',
    'CNY',
    'EUR',
    'GBP',
    'ILS',
    'INR',
    'JPY',
    'MXN',
    'NGN',
    'TRY',
    'USD',
    'XAG',
    'XAU',
    'ZAR',
]

[propagator]
updates_channel_name = "nano:timeseries:updates"
prices_channel_name = "nano:prices:updates"
prices_latest_key = "nano:prices:latest"
updates_key = "nano:timeseries:latest"